[general]
artifact-dir = "dist"

[cachix]
cache-name = "agaia"
publish = true

[env]
# TODO: setting these actually does nothing, need to set in nix builds
RUST_BACKTRACE = "1"
CARGO_TERM_COLOR = "1"
CLICOLOR = "1"

[build]
outputs = [
  "checks",
  "packages",
  "devShells",
  "homeConfigurations",
  "darwinConfigurations",
  "nixosConfigurations",
  "defaultPackage",
  "devShell",
]
artifacts = ["packages.*.!formatter"]
systems = ["x86_64-linux", "x86_64-darwin"]

[[output]]
name = "packages.*.default"
extra-prereqs = [
  "checks.*.cargo-clippy",
  "checks.*.cargo-audit",
  "checks.*.cargo-deny",
  "checks.*.cargo-nextest",
  "checks.*.fake",
]

[[output]]
name = "checks.*.fake"
extra-prereqs = ["checks.*.foo", "checks.*.bar"]

#[[output]]
# TODO
# CI requires this package
#name = "devShells.*.ci"
#extra-prereqs = ["packages.*.default"]
